---
name: Push feature/hotfix

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'CODEOWNERS'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  terraform_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    if: github.event.repository.name != 'template-terraform'
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Install
        id: terraform_install
        uses: dustindortch/template-terraform/.github/actions/terraform_install@main

      - name: Terraform Init
        id: terraform_init
        uses: dustindortch/template-terraform/.github/actions/terraform_init@main

      - name: Terraform Validate
        id: terraform_validate
        uses: dustindortch/template-terraform/.github/actions/terraform_validate@main

      - name: Terraform Format
        id: terraform_fmt
        uses: dustindortch/template-terraform/.github/actions/terraform_fmt@main
...
